kind: pipeline
name: hello-world123
type: docker

steps:
  - name: say-hello
    image: node:latest
    commands:
      - npm install
      - npm run start:test
      - node test.js
      - npm run test

  # - name: say-hello2
  #   image: node:latest
  #   commands:
  #     - bash test2.sh
  #     - npm install
  #     - npm run standard-test
  # 